name: demandregio
channels:
  - conda-forge
dependencies:
  - python
  - pip
  
  - numpy
  - pandas
  - pytables
  - pyyaml
  - requests
  
  - geopandas
  - descartes
  - xarray
  
  - matplotlib

  - ipython
  - jupyter