name: disaggregator
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  
  - numpy
  - pandas
  - pytables
  - pyyaml
  - requests
  
  - geopandas
  - descartes
  - xarray
  
  - matplotlib
  
  # Jupyter Environment
  - jupyterlab
  - notebook
  - ipython
